# ASAP7 area synthesis flow for cpu_core (Yosys) -- SRAM-blackbox variant.
#
# Cache/predictor arrays stay as unmapped $mem cells (memory -nomap), so the
# stat -liberty area below covers logic + flops only.  The missing piece for
# the plan.md ENV-04 main metric is the ASAP7 SRAM macro area for those
# arrays: the JOIN-06 report script must add it from the asap7_sram_0p0
# macro library (fixed under third_party/asap7/sram_0p0/generated/LIB/),
# matching each array size to the closest macro.  Register-based upper
# bound: synth.tcl.
#
# Usage: yosys -p "tcl synth/synth_bb.tcl <fe> <be> <phys_regs> <rob_entries> <outdir>"

yosys -import

set fe_width    [lindex $argv 0]
set be_width    [lindex $argv 1]
set phys_regs   [lindex $argv 2]
set rob_entries [lindex $argv 3]
set outdir      [lindex $argv 4]
set rs_entries  [lindex $argv 5]
set lsq_entries [lindex $argv 6]
set cache_stats [lindex $argv 7]
set mul_impl    [lindex $argv 8]
set enable_caches [lindex $argv 9]
if {$rs_entries eq ""}  { set rs_entries 8 }
if {$lsq_entries eq ""} { set lsq_entries 8 }
if {$cache_stats eq ""} { set cache_stats 0 }
if {$mul_impl eq ""}    { set mul_impl 0 }
if {$enable_caches eq ""} { set enable_caches 1 }
set libdir      "_asap7_lib_filtered"

file mkdir $outdir

set f [open "rtl/filelist.f" r]
set rtl_files {}
while {[gets $f line] >= 0} {
    if {[string trim $line] ne ""} { lappend rtl_files [string trim $line] }
}
close $f

read_verilog -I rtl {*}$rtl_files
chparam -set FE_WIDTH $fe_width -set BE_WIDTH $be_width \
        -set PHYS_REGS $phys_regs -set ROB_ENTRIES $rob_entries \
        -set RS_ENTRIES $rs_entries -set LSQ_ENTRIES $lsq_entries \
        -set ENABLE_CACHE_STATS $cache_stats -set MUL_IMPL $mul_impl \
        -set ENABLE_CACHES $enable_caches cpu_core
hierarchy -check -top cpu_core
procs
opt
fsm
opt
memory -nomap
# Preserve the memory geometry and port counts before technology mapping.  The
# post-run audit treats every one of these cells as unpriced until an SRAM,
# banked/replicated macro implementation, or explicit standard-cell mapping is
# assigned.
tee -o $outdir/memory_manifest.il dump {t:$mem*}
techmap
opt
# Legalize flops before the final combinational mapping.  The usable ASAP7
# positive-edge cell exposes QN, so dfflibmap introduces polarity/input-select
# logic.  Mapping flops after ABC left that logic as unpriced $_NOT_/$_MUX_.
dfflibmap -liberty $libdir/asap7sc7p5t_SEQ_RVT_TT_nldm_201020.lib
opt
# ABC's bundled liberty->genlib conversion cannot ingest ASAP7 NLDM libs
# (&nf crashes, map/if see "only 2 cell classes").  Use a generated SIS genlib
# + classic `map` for all remaining combinational logic.
# genlib generated by tools/liberty2genlib.py; area cost is scaled x10000 there
# and stat -liberty below reads the LEF-normalized filtered liberty files.
abc -genlib _asap7_lib_filtered/asap7_comb.genlib \
    -script "+strash;scorr;dc2;dretime;strash;map"
opt

tee -o $outdir/synth.log stat -liberty $libdir/asap7sc7p5t_INVBUF_RVT_TT_nldm_201020.lib \
    -liberty $libdir/asap7sc7p5t_SIMPLE_RVT_TT_nldm_201020.lib \
    -liberty $libdir/asap7sc7p5t_AO_RVT_TT_nldm_201020.lib \
    -liberty $libdir/asap7sc7p5t_OA_RVT_TT_nldm_201020.lib \
    -liberty $libdir/asap7sc7p5t_SEQ_RVT_TT_nldm_201020.lib
write_verilog -noattr $outdir/cpu_core_synth.v
tee -o $outdir/stat_after_abc.log stat
